version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    # network_mode: "host"
    environment:
      MYSQL_DATABASE: 'aiplat'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    # ports:
    #   - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    # network_mode: "host"
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb

volumes:
  db_data: