# 使用官方的Python镜像作为基础镜像
FROM python:3.12

# 设置工作目录
WORKDIR /app

# 复制项目依赖文件
COPY requirements.txt /app/

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目代码到容器中
COPY . /app/

# 暴露端口
EXPOSE 8001

# 运行Django开发服务器
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]