# Generated by Django 5.1.6 on 2025-02-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custommodel', '0003_alter_message_options_message_user_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=6, null=True)),
                ('sendtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
